# from template sproogen/modern-resume-theme
# Content configuration version
version: 2

# Personal info
name: Kevin Chu
title: PhD Candidate in Materials Science | Georgia Tech
email: kchu41@gatech.edu

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  kvnchv
linkedin_username: chukgatech
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll
orcid_username: 0000-0003-1929-710X

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=HJXYzrYAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
  I study fundamental deformation and strengthening mechanisms at the nano and mesoscale to inform the design of alloys. 
  I leverage existing codebases and implement novel computational approaches as necessary to enhace predictive simulation capabilities. 
  Skills honed during my PhD include:
  - Molecular Dynamics/Monte Carlo methods (<mark>LAMMPS</mark>)
  - Concurrent Atomistic-Continuum multiscale modeling (<mark>CAC</mark>)
  - Data analysis and visualization (<mark>Scipy</mark>, <mark>Jupyter</mark>, <mark>Pandas</mark>)
  - Scientific software development (<mark>MPI</mark>, <mark>Fortran90</mark>, <mark>C++</mark>)
  - Scripting and automation (<mark>Python</mark>, <mark>BASH</mark>)

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Georgia Institute of Technology
        caption: 2017 - 2022
        sub_title: PhD Materials Science and Engineering
        description: PhD Advisor - David L. McDowell
      - layout: top
        title: University of California, Los Angeles
        caption: 2013 - 2017
        sub_title: B.S. Materials Science and Engineering
        description: Undergraduate Advisor - Jaime Marian

  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        # link_text: boringcompany.com
        sub_title: Graduate Research Assistant
        caption: August 2017 - Present
        description: | # this will include new lines to allow paragraphs
          - Identified the link between average-atom EAM potentials and concurrent atomistic-continuum (CAC) coarse-grained models, designed and executed validation simulations
          - Contributed to open-source fork of LAMMPS codebase to implement necessary features for finite-temperature alloy simulations
          - Collaborated with national labs and various university research partners to paint a cohesive picture of deformation in additively-manufactured 316L stainless steels
      - layout: left
        title: U.S. Naval Research Laboratory
        sub_title: NREIP Graduate Fellowship
        caption: Summer 2021
        description: | # this will include new lines to allow paragraphs
          - Selected for Naval Research Enterprise Intern Program (NREIP) at the US Naval Research Lab.
          - Designed efficient large-scale Monte-Carlo (MC) annealing algorithms to develop short-range solute ordering in complex alloy systems.
          - Created a Python-based workflow to process both atom-probe tomography datasets and MC-computed microstructures to directly quantify cluster size and distributions. 
      - layout: left
        title: Sandia National Laboratories
        sub_title: R&D Graduate Intern
        caption: Summer 2019
        description: |
          - Designed rastering algorithm for computing interstitial and substitutional solute site binding energies
          - Executed large scale parametric dislocation mobility simulations and analyses in 3XX stainless steels
          - Theorized and implemented a continuum-scale diffusion model for Cottrell atomosphere formation kinetics.
      - layout: left
        title: Sandia National Laboratories
        sub_title: R&D Undergraduate Intern
        caption: Summer 2017
        description: |
          - Designed and executed molecular dynamics simulations of epitaxially grown crystalline materials using LAMMPS and high performance computing clusters. 
          - Discovered correlation between surface pitting defects and interface dislocation nucleation. 

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: (2022) Multiscale Concurrent Atomistic-Continuum (CAC) modeling of multicomponent alloys
        sub_title: K. Chu, A. Diaz, Y. Chen, T. Zhu, and D. L. McDowell, Computational Materials Science, 201 (2022).
        link: https://doi.org/10.1016/j.commatsci.2021.110873
      - layout: top
        title: (2020) Temperature and composition dependent screw dislocation mobility in austenitic stainless steels from large-scale molecular dynamics
        sub_title: K. Chu, M. E. Foster, R. B. Sills, X. Zhou, T. Zhu, and D. L. McDowell, npj Computational Materials, 6(1) (2020).
        link: https://doi.org/10.1038/s41524-020-00452-x
      - layout: top
        title: (2020) Molecular Statics Analyses of Thermodynamics and Kinetics of Hydrogen Cottrell Atmosphere Formation Around Edge Dislocations in Aluminum
        sub_title: C. D. Spataru, K. Chu, R. B. Sills, and X. Zhou, JOM, 72(8) (2020).
        link: https://doi.org/10.1007/s11837-020-04213-5
      - layout: top
        title: (2018) Molecular dynamics studies of InGaN growth on nonpolar (11-20) GaN surfaces
        sub_title: K. Chu, J. Gruber, X. W. Zhou, R. E. Jones, S. R. Lee, and G. J. Tucker, Phys. Rev. Materials, 2(1) (2018).
        link: https://doi.org/10.1103/PhysRevMaterials.2.013402
      - layout: top
        title: (2017) Polymorphic improvement of Stillinger-Weber potential for InGaN
        sub_title: X. W. Zhou, R. E. Jones, and K. Chu, Journal of Applied Physics, 122(23), (2017).
        link: https://doi.org/10.1063/1.5001339

  - title: Teaching Experience
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Teaching Capstone
        sub_title: Center for Teaching and Learning, Georgia Tech
        caption: Fall 2021
        description: | # this will include new lines to allow paragraphs
          - Delivered on-demand video lecture module describing deformation geometry and analysis for MSE 3005 Mechanical Behavior of Materials
          - Leveraged atomic visualization software to enhance 3D spatial recognition of fundamental materials concepts (slip systems)
      - layout: left
        title: Teaching Assistant
        sub_title: Materials Science and Engineering, Georgia Tech
        caption: Spring 2018 - Present
        description: | # this will include new lines to allow paragraphs
          - Led discussion sections, hosted office hours, and graded exams for undergraduate courses 
          - Principles and Applications of Engineering Materials (2018, 2019, 2020)
          - Mechanical Behavior of Materials (2020, 2021)

      - layout: left
        title: Teaching Practicum
        sub_title: Materials Science and Engineering, Georgia Tech
        caption: Fall 2019
        description: | # this will include new lines to allow paragraphs
          - Delivered lecture materials with the support of a dedicated faculty teaching mentor (MSE 3005).
          - Developed take-home assignments as well as a exam materials relevant to the delivered course segment
  - title: Conference Presentations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Enabling Accurate Coarse-grained Atomistic Simulation of Defect Behavior in Random Alloys
        sub_title: Chu, K., Diaz, A., Chen, Y., McDowell, D. L. (2021)
        caption: Materials Science and Technology 2021, Columbus, OH
      - layout: top
        title: Application of the concurrent atomistic-continuum (CAC) method to dislocation reaction pathway modeling in FCC metals.
        sub_title: Chu, K., Chen, D., Diaz, A., Selimov, A., Chen, Y., Zhu, T., McDowell, D. L. (2019)
        caption: Materials Science and Technology 2019, Portland, OR

#  - title: Teaching
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
